### ISSUE TITLE
Fails to build from source on arm64/ppc64el: tests/generate_sequence

### ISSUE THREAD

**Issue by mr-c** [gmarcais/Jellyfish#109]
See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=890137

```
...
FAIL: tests/generate_sequence
=============================

Seed: 3141592653
Creating fasta file 'seq10m.fa'
Seed: 1040104553
Creating fasta file 'seq1m_0.fa'
Creating fasta file 'seq1m_1.fa'
Creating fasta file 'seq1m_2.fa'
Creating fasta file 'seq1m_3.fa'
Creating fasta file 'seq1m_4.fa'
Seed: 1473540700
Creating fastq file 'seq10m.fq'
Usage: fastq2sam [options] fastq:string+
Use --help for more information
FAIL tests/generate_sequence.sh (exit status: 1)

SKIP: tests/big
===============

Skip big test
SKIP tests/big.sh (exit status: 77)

SKIP: tests/sam
===============

Skip SAM/BAM/CRAM file format test
SKIP tests/sam.sh (exit status: 77)

SKIP: tests/swig_python
=======================

SKIP tests/swig_python.sh (exit status: 77)

SKIP: tests/swig_ruby
=====================

SKIP tests/swig_ruby.sh (exit status: 77)

============================================================================
Testsuite summary for jellyfish 2.2.7
============================================================================
# TOTAL: 14
# PASS:  9
# SKIP:  4
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See ./test-suite.log
Please report to gmarcais@umd.edu
============================================================================
Makefile:2280: recipe for target 'test-suite.log' failed
make[4]: *** [test-suite.log] Error 1
```
https://buildd.debian.org/status/fetch.php?pkg=jellyfish&arch=arm64&ver=2.2.7-1&stamp=1517870355&raw=0
https://buildd.debian.org/status/fetch.php?pkg=jellyfish&arch=ppc64el&ver=2.2.7-1&stamp=1517870160&raw=0

**Comment by mr-c** [comment]
P.S. Thanks for the new release! :-)

**Comment by gmarcais** [comment]
I don't seem to be able to reproduce that bug. This is what I get after `generate_sequence.sh` ran:

```
gus@gus-laptop ~/D/U/j/build  0 > ll build-gcc/default/tests/ | grep seq10m
-rw-r--r-- 1 gus users  11M Feb 12 15:15 seq10m.bam
-rw-r--r-- 1 gus users 9.0M Feb 12 15:15 seq10m.cram
-rw-r--r-- 1 gus users 9.7M Feb 12 15:15 seq10m.fa
lrwxrwxrwx 1 gus users    9 Feb 12 15:15 seq10m.fastq -> seq10m.fq
-rw-r--r-- 1 gus users  22M Feb 12 15:15 seq10m.fq
-rw-r--r-- 1 gus users  24M Feb 12 15:15 seq10m.sam
```

Are `seq10m.fq` and the symlink `seq10m.fastq` present?

**Comment by mr-c** [comment]
@gmarcais What processor architecture did you test with? This test passes on AMD64 but not arm64 or ppc64el (amongst others: https://buildd.debian.org/status/package.php?p=jellyfish )

**Comment by gmarcais** [comment]
Can you try the develop branch? This bug should be fixed.

**Comment by mr-c** [comment]
@gmarcais Yes, the build works on arm64 and ppc64el now https://buildd.debian.org/status/package.php?p=jellyfish

Looks like we're still getting test failures on armhf, i386, s390x  and others..

**Comment by gmarcais** [comment]
I don't have access to all these architectures. What would be the easiest way to setup a similar testing framework as the one Debian is using?

**Comment by mmokrejs** [comment]
```
Usage: fastq2sam [options] fastq:string+
Use --help for more information
FAIL tests/generate_sequence.sh (exit status: 1)
```

@mr-c So what is `fastq2sam`? Where does it come from? Do you have proper version needed for the test? (I do not have fastq2sam at all so cannot say).
